### ISSUE TITLE
How to handle context with Rasa Core?

### ISSUE THREAD

**Issue by Selvaganapathi06** [RasaHQ/rasa_core#279] opened 2018-03-17 12:58 UTC
As mentioned Serve.py, used to implement bot but integrate with UI got below issue

 Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
i have installed flask cors and added cross-origin code in serve.py file but not resolve my issues. Please share me how to resolve this issues?

**Comment by Selvaganapathi06** [comment] 2018-03-19 12:57
Thanks. Cross origin issue was fixed.

**Comment by Selvaganapathi06** [comment] 2018-03-19 12:58
Can you please tell me how to handle context in rasa_core my custom chat bot? How to use tracker, slot in custom bot? please share any examples

**Comment by tmbo** [comment] 2018-03-21 11:56
Did you take a look at the examples that are part of the documentation, e.g. https://core.rasa.com/tutorial_supervised.html 

You can set slots as part of your actions. The values will influence the dialogue predictions depending on their value and type. (more info about this can be found in the slots section of the docs). Let me know if you have any more specific questions, or things you didn't understand.

**Comment by Selvaganapathi06** [comment] 2018-03-21 12:09
one more question? how to create custom polices? and how to set default responses for untrained question?

**Comment by Selvaganapathi06** [comment] 2018-03-21 12:14
Hi TOm
i read this link
https://lastmile-rasa-dm.readthedocs-hosted.com/en/latest/plumbing.html

I took example for bot_custom.py
https://github.com/souvikg10/rasa_bot_example/blob/master/bot_custom.py

i need to create custom policy. i took example for class SimplePolicy(Policy):
def predict_action_probabilities(self, tracker, domain):
    # type: (DialogueStateTracker, Domain) -> List[float]

    responses = {
        "greet": 3,
    }

    if tracker.latest_action_name == ACTION_LISTEN_NAME:
        key = tracker.latest_message.intent["name"]
        action = responses[key] if key in responses else 2
        return utils.one_hot(action, domain.num_actions)
    else:

the above code how to give in my response
that response only gave greet only

**Comment by amn41** [comment] 2018-03-21 12:19
@Selvaganapathi06 where did you find those docs? it's a really ancient version. http://core.rasa.com/ has the up-to-date docs

**Comment by Selvaganapathi06** [comment] 2018-03-21 12:24
how to create custom policy ? give any example?. especially need to give my responses?
one more question how set default response for untrained questions?

**Comment by amn41** [comment] 2018-03-21 12:26
please see 
https://github.com/RasaHQ/rasa_core/issues/137

**Comment by Selvaganapathi06** [comment] 2018-03-21 12:28
thanks for the  default response. how to create custom policy ? give any example?. especially need to give my responses?

**Comment by amn41** [comment] 2018-03-21 12:36
responses are defined in the domain. There is an up-to-date tutorial here: http://core.rasa.com/tutorial_basics.html

**Comment by Selvaganapathi06** [comment] 2018-03-21 12:40
sorry Aalan, in my question is the below is my policy for example,
class ExamplePolicy(Policy):
    def predict_action_probabilities(self, tracker, domain):
       

        responses = {
            "greet": 3,
        }

        if tracker.latest_action_name == ACTION_LISTEN_NAME:
            key = tracker.latest_message.intent["name"]
            action = responses[key] if key in responses else 2
            return utils.one_hot(action, domain.num_actions)
        else:
            return np.zeros(domain.num_actions)

the mentioned       responses = {
            "greet": 3,
        }
how to give in my responses

**Comment by Selvaganapathi06** [comment] 2018-03-21 12:43
one more qustion, in my bot some of Q&A is yes or no based, but not working properly yes or no questions.

**Comment by Selvaganapathi06** [comment] 2018-03-22 11:40
How to call above mentioned fallback function using keras policy .i have created a policy like restaurant policy example which is based on keras policy

**Comment by Selvaganapathi06** [comment] 2018-03-23 09:55
i saw issue no Reg:137 based  on suggestion i added my code. but finally got this error.

File "serve1.py", line 164, in <module>
    train_dialogue()
  File "serve1.py", line 108, in train_dialogue
    validation_split=0.2
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/agent.py", line 152, in train
    trainer.train(filename, remove_duplicates=remove_duplicates, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/policies/trainer.py", line 53, in train
    self.ensemble.train(training_data, self.domain, self.featurizer, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/policies/ensemble.py", line 54, in train
    Policy.prepare(featurizer,
AttributeError: 'MyPolicy' object has no attribute 'prepare'

**Comment by NicoHood** [comment] 2018-07-29 22:21
I only found this github issue about using context with rasa core, but I still dont know how to handle it.

Lets contruct a simple usecase:
* User asks for the temperature
   - The bot asks if the user is inside or outside (yes/no)
      * The bot reports the temperature

But how can I tell rasa that this yes/no question is no "normal" intent? I want to forbid something like this:
* The user writes yes/no
    * (undefined?!?) The bot reportes the temperature

2nd usecase (just a different example, if the above was not clear):
* the user asks for the weather
   - the bot asks in which town
     * the bot reports the weather in the selected town

Now if you just enter the town, without asking for the weather, it will still trigger the weather option:
* user selects town New York
  (undefined!?) Bot reports weather?
  OR bot safes town, but waites for a weather request!? -> what if a too long time was passed and the town slot information is way too old?

Any hints on how to handle such a flow? I also want to clear any used slot, because I do not want to keep any yes/no decision that was answered 10 days ago, and with a new request the bot still assumes the same yes/no.

To me it looks like the examples only cover very simple question -> response use cases, but this seem incomplete or unsupported to me.

**Comment by amn41** [comment] 2018-07-30 19:45
Does this help? http://rasa.com/docs/core/slotfilling/

**Comment by NicoHood** [comment] 2018-07-31 11:14
Okay I tried to understand the linked doc, but I am still not sure how to handle my scenario with rasa.

My usecase:
I want to create a partybot that can inform users about parties, register them for a party and me as administrator/host can create new party events.

First I want to create a new party event. I have to provide `party` (name), `time` (date and time), `limit` (guest limit) and `newsletter` (an initial newsletter sent to all registered members).

The problem I am facing is, that the bot recognizes my intent `create_party` and then executes the FormAction. It asks for the newsletter first, which is okay so far.

What I expect the bot to do is to take the user input and simply but it into the slot. But it will rather listen for all available intents:
```
erstelle eine neue party
/home/arch/.local/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
------
Chat history:

	bot did:	None

	bot did:	action_listen

	user said:	erstelle eine neue party

		 whose intent is:	create_party

we currently have slots: datetime: None, limit: None, newsletter: None, party: None, requested_slot: None

------
The bot wants to [utter_greet] due to the intent. Is this correct?

	1.	Yes
	2.	No, intent is right but the action is wrong
	3.	The intent is wrong
	0.	Export current conversations as stories and quit
2
------
Chat history:

	bot did:	None

	bot did:	action_listen

	user said:	erstelle eine neue party

		 whose intent is:	create_party

we currently have slots: datetime: None, limit: None, newsletter: None, party: None, requested_slot: None

------
what is the next action for the bot?

         0                           action_listen    0.19
         1                          action_restart    0.06
         2                 action_default_fallback    0.01
         3                             utter_greet    0.78
         4                               utter_bye    0.47
         5              utter_register_party_guest    0.11
         6                         utter_ask_party    0.35
         7             action_register_party_guest    0.01
         8                     action_create_party    0.01
8
thanks! The bot will now [action_create_party]
 -----------
Processed trackers: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 739.48it/s, # actions=2]
[...]
Bitte gebe den Party Newsletter ein.
------
Chat history:

	bot did:	None

	bot did:	action_listen

	user did:	create_party

	bot did:	action_create_party

we currently have slots: datetime: None, limit: None, newsletter: None, party: None, requested_slot: newsletter

------
The bot wants to [action_listen]. Is this correct?

	1.	Yes.
	2.	No, the action is wrong.
	0.	Export current conversations as stories and quit
1
Next user input:
am freitag machen wir wieder eine coole party
/home/arch/.local/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
------
Chat history:

	bot did:	action_listen

	user did:	create_party

	bot did:	action_create_party

	bot did:	action_listen

	user said:	am freitag machen wir wieder eine coole party

		 whose intent is:	register_party_guest

	with time:	2018-08-03T00:00:00.000Z

we currently have slots: datetime: None, limit: None, newsletter: None, party: None, requested_slot: newsletter

------
The bot wants to [utter_greet] due to the intent. Is this correct?

	1.	Yes
	2.	No, intent is right but the action is wrong
	3.	The intent is wrong
	0.	Export current conversations as stories and quit
```

So how can I solve this? Should I rather use `input()` calls in my python code to extract user input directly from the command line (I guess this will not work, if you want to move the bot to telegram/slack etc). But how can I make the bot to NOT interpret the data it is asking for?

```python
from rasa_core.actions.forms import (
    BooleanFormField,
    EntityFormField,
    FormAction,
    FreeTextFormField
)

class ActionCreateParty(FormAction):

    RANDOMIZE = False

    @staticmethod
    def required_fields():
        return [
            EntityFormField("newsletter", "newsletter"),
            EntityFormField("time", "datetime"),
            EntityFormField("number", "limit"),
            EntityFormField("party", "party"),
        ]

    def name(self):
        return 'action_create_party'

    def submit(self, dispatcher, tracker, domain):
        response = """Erstelle Party {} am {} für {} Personen. Der Newsletter heisst: {}""".format(
            tracker.get_slot("party"),
            tracker.get_slot("datetime"),
            tracker.get_slot("limit"),
            tracker.get_slot("newsletter")
        )

        dispatcher.utter_message(response)
        return [SlotSet("search_results", results)]
```

**Comment by amn41** [comment] 2018-08-02 18:47
@NicoHood what do your stories look like? It looks like NLU is picking up the correct intent but the predicted action is wrong, which would suggest the problem is in your Rasa Core model. For help with this, I would recommend posting in the [community forum](https://forum.rasa.com)

**Comment by akelad** [comment] 2018-08-03 07:37
I'll close this for now then, since it's more of a community forum post :)

**Closed by akelad** 2018-08-03 07:37 UTC
Labels: question
