### ISSUE TITLE
Trigger fallback policy when ActionListen is predicted after a user utterance

### ISSUE THREAD

**Issue by JoeyFaulkner** [RasaHQ/rasa_core#749] opened 2018-07-16 11:52 UTC
Because generally the most commonly predicted action is ActionListen, when the bot is out of its comfort zone it may just predict ActionListen after a user utterance, which doesn't help the conversation move along. It should go to fallback policy in this case.
Case when this should happen:
1. if there’s a fallbackpolicy present AND
2. if there was just a user message AND
3. the predicted action is action_listen AND
4. it wasn't predicted by the memo policy

**Comment by raghavendrav1210** [comment] 2018-08-22 10:47
@akelad @tmbo when can we expect this? Are there any workarounds?

**Comment by amn41** [comment] 2018-08-22 12:56
if this is happening, it means your model isn't performing well. 

When we implement this fix, rasa core will predict a different action, but this **won't fix the root cause of your problem**, it just means that rasa core won't appear to fail silently.

**Comment by akelad** [comment] 2018-08-27 10:00
Update: working on this, but need to add some info to ActionExecuted events to show which policy predicted the next event

**Comment by akelad** [comment] 2018-09-03 11:28
Update: implemented, but needs cleaning up a bit, then i'll create the PR

**Closed** 2018-09-07 12:10 UTC
Labels: :wrench: maintenance
