### ISSUE TITLE
Slack vs Facebook response time

### ISSUE THREAD

**Issue by FellowNico** [RasaHQ/rasa_core#1164] opened 2018-10-12 14:21 UTC
Hello folks,

I implemented a bot interfaced with facebook messenger and Slack.
I noticed some difference between the time needed to get the response from the bot on slack and from the bot on messenger. 
The app is hosted on heroku.

**Rasa Core version**:
0.11.12
**Python version**: 
3.6.6
**Operating system** (windows, osx, ...):
Heroku dyno
**Issue**:
As I can see in the heroku logs the time needed until seeing the output in the chat is really different.

With a simple text response => Facebook takes almost ~2 or 3sec
                                              => Slack ~less than 1sec 

Protocol used: 
HTTPS (for both)

command used  through Procfile: 
`python -m rasa_core.run -d models/dialogue -u models/nlu --port $PORT --credentials credentials.yml`

I tried to only serve facebook channel using the -c flag but the response time doesn't change.
I also tried scaling my dynos, but doesn't change anything.

So I wanted to know if it comes from the implementation or something else.
Please enlighten me
**Why is there such a difference between them ?**

### facebook
`2018-10-12T14:12:42.445862+00:00 app[web.1]: 2018-10-12 14:12:42 INFO     rasa_core.channels.facebook  - Sending message: Que la force soit avec toi, qu'elle te permette de trouver la bonne rÃ©ponse.
2018-10-12T14:12:43.384780+00:00 app[web.1]: 10.122.146.14 - - [2018-10-12 14:12:43] "POST /webhooks/facebook/webhook HTTP/1.1" 200 122 0.945207

2018-10-12T14:12:43.385277+00:00 heroku[router]: at=info method=POST path="/webhooks/facebook/webhook" host=X.herokuapp.com request_id=x fwd="x.x.x.12" dyno=web.1 connect=0ms service=946ms status=200 bytes=122 protocol=https

2018-10-12T14:12:43.833526+00:00 heroku[router]: at=info method=POST path="/webhooks/facebook/webhook" host=X.herokuapp.com request_id=131ac865-6936-4cfd-be43-c77b0d94d8e6 fwd="x.x.x.2" dyno=web.2 connect=0ms service=3ms status=200 bytes=122 protocol=https

2018-10-12T14:12:43.834472+00:00 app[web.2]: 10.11.36.46 - - [2018-10-12 14:12:43] "POST /webhooks/facebook/webhook HTTP/1.1" 200 122 0.001772`
### slack
`2018-10-12T14:14:19.263540+00:00 heroku[router]: at=info method=POST path="/webhooks/slack/webhook" host=X.herokuapp.com request_id=6f3f7a54-a8fd-422a-8a7e-4c0f35f8ebf5 fwd="x.x.x.255" dyno=web.2 connect=4ms service=177ms status=200 bytes=115 protocol=https

2018-10-12T14:14:19.263060+00:00 app[web.1]: 10.99.61.232 - - [2018-10-12 14:14:19] "POST /webhooks/slack/webhook HTTP/1.1" 200 115 0.175297

2018-10-12T14:14:19.572039+00:00 heroku[router]: at=info method=POST path="/webhooks/slack/webhook" host=1  request_id=915af4ca-d25d-480e-b089-f152d9627b3a fwd="x.x.x.29" dyno=web.1 connect=0ms service=2ms status=200 bytes=115 protocol=https

2018-10-12T14:14:19.571942+00:00 app[web.1]: 10.11.34.32 - - [2018-10-12 14:14:19] "POST /webhooks/slack/webhook HTTP/1.1" 200 115 0.000896`

Thank you

**Comment by bbreton3** [comment] 2018-10-13 15:35
Same issue here, referenced it on [Stackoverflow](https://stackoverflow.com/questions/52794537/facebook-messenger-slow-response-time-with-rasa-core)

**Comment by akelad** [comment] 2018-10-15 08:32
Thanks for raising this issue, @ricwo  will get back to you about it soon.

**Comment by ricwo** [comment] 2018-10-15 19:37
@FellowNico @bbreton3 both the Slack and Facebook channels call the relevant APIs with a simple `requests.post()`, so I don't think the difference in response time is related to Rasa Core. Have you raised this issue on the Facebook developer page?

In the meantime can you replace the `send()` function in `facebook.py` ([link](https://github.com/RasaHQ/rasa_core/blob/0.11.12/rasa_core/channels/facebook.py#L125)) with the following code and post the command line output? That way we can have a look at how long the actual facebook API call takes, as opposed to Rasa Core.

```python
    def send(self, recipient_id, element):
        import time
        start = time.clock()
        self.messenger_client.send(element.to_dict(),
                                   {"sender": {"id": recipient_id}},
                                   'RESPONSE')
        print("POST /me/messages response time {:.4g} s".format(time.clock() - start))
```

**Comment by bbreton3** [comment] 2018-10-16 16:04
@ricwo @FellowNico The response time from Facebook seems to be quick, here is what I have:

> POST /me/messages response time 0.02074 s

The bottleneck here seems to be the first POST request to Facebook from rasa_core:

> [2018-10-16 15:59:12] "POST /webhooks/facebook/webhook HTTP/1.1" 200 122 0.966870

I am investigating to see why, If you guys have any idea what in rasa_core could take so much time in the facebook channel pipeline.

**Comment by ricwo** [comment] 2018-10-19 15:33
@bbreton3 Okay, would you mimd also timing the `def webhook()` method in facebook.py? e.g. replace it with 
```python
@fb_webhook.route("/webhook", methods=['POST'])
        def webhook():
            import time
            signature = request.headers.get("X-Hub-Signature") or ''

            start_sig = time.clock()
            valid_sig = self.validate_hub_signature(self.fb_secret,
                                                    request.data,
                                                    signature)
            print("Hub signature validation took {:.4g} s".format(time.clock()
                                                                  - start_sig))
            if not valid_sig:
                logger.warning("Wrong fb secret! Make sure this matches the "
                               "secret in your facebook app settings")
                return "not validated"

            start_messenger_init = time.clock()
            messenger = Messenger(self.fb_access_token, on_new_message)
            print("Messenger initialisation took {:.4g} s".format(
                    time.clock() - start_messenger_init))

            start_message_handling = time.clock()
            messenger.handle(request.get_json(force=True))
            print("Message handling took {:.4g} s".format(
                    time.clock() - start_messenger_init))

            return "success"
```

**Comment by bbreton3** [comment] 2018-10-19 16:16
I already did, I timed the 4 steps of the webhook, and it seems fast enougs:

> 2018-10-17T16:19:17.479353+00:00 app[web.1]: Webhook:
> 2018-10-17T16:19:17.479356+00:00 app[web.1]: signature 4.7e-05 s
> 2018-10-17T16:19:17.479358+00:00 app[web.1]: validate 0.000479 s
> 2018-10-17T16:19:17.479359+00:00 app[web.1]: create_messenger 0.000471 s
> 2018-10-17T16:19:17.479361+00:00 app[web.1]: handle_messenger 0.04649

As for the webhook, it is called twice for every message, I am not sure why.
I also deployed a similar bot on another platform (dialogflow), an I don't have the response time issue on messenger, so I am sure it doesn't come from Facebook

**Comment by ricwo** [comment] 2018-10-20 16:32
@bbreton3 do you know what the overall response time was for the timings you just posted? Because I'm not sure which other process could lead to a response time of 2-3 seconds that you reported initially.

**Comment by bbreton3** [comment] 2018-10-20 21:36
The complete log from heroku is the following:

> 2018-10-17T16:17:31.039814+00:00 app[web.1]: 10.111.224.2 - - [2018-10-17 16:17:31] "POST /webhooks/facebook/webhook HTTP/1.1" 200 122 2.163950
2018-10-17T16:19:15.443430+00:00 app[web.1]: 2018-10-17 16:19:15 INFO     rasa_core.channels.facebook  - FacebookInputwebhook
2018-10-17T16:19:15.443845+00:00 app[web.1]: 2018-10-17 16:19:15 INFO     rasa_core.channels.facebook  - FacebookInputvalidate_hub_signature
2018-10-17T16:19:15.444163+00:00 app[web.1]: 2018-10-17 16:19:15 INFO     rasa_core.channels.facebook  - Messenger__init__
2018-10-17T16:19:15.444925+00:00 app[web.1]: 2018-10-17 16:19:15 INFO     rasa_core.channels.facebook  - Messengermessage
2018-10-17T16:19:15.445134+00:00 app[web.1]: 2018-10-17 16:19:15 INFO     rasa_core.channels.facebook  - Messenger_handle_user_message
2018-10-17T16:19:15.445365+00:00 app[web.1]: 2018-10-17 16:19:15 INFO     rasa_core.channels.facebook  - MessengerBot__init__
2018-10-17T16:19:15.445647+00:00 app[web.1]: 2018-10-17 16:19:15 DEBUG    rasa_core.tracker_store  - Recreating tracker for id '2204189702989811'
2018-10-17T16:19:15.448265+00:00 app[web.1]: 2018-10-17 16:19:15 DEBUG    rasa_core.processor  - Received user message 'elementaire mon cher watson' with intent '{'name': 'sherlock_holmes', 'confidence': 0.9350796341896057}' and entities '[]'
2018-10-17T16:19:15.448522+00:00 app[web.1]: 2018-10-17 16:19:15 DEBUG    rasa_core.processor  - Logged UserUtterance - tracker now has 6 events
2018-10-17T16:19:15.448827+00:00 app[web.1]: 2018-10-17 16:19:15 DEBUG    rasa_core.processor  - Current slot values:
2018-10-17T16:19:15.448831+00:00 app[web.1]: 
2018-10-17T16:19:15.449263+00:00 app[web.1]: 2018-10-17 16:19:15 DEBUG    rasa_core.policies.memoization  - Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_sherlock_holmes': 1.0}, {'prev_utter_sherlock_holmes': 1.0, 'intent_sherlock_holmes': 1.0}, {'prev_action_listen': 1.0, 'intent_sherlock_holmes': 1.0}]
2018-10-17T16:19:15.449528+00:00 app[web.1]: 2018-10-17 16:19:15 DEBUG    rasa_core.policies.memoization  - There is no memorised next action
2018-10-17T16:19:15.453328+00:00 app[web.1]: 2018-10-17 16:19:15 DEBUG    rasa_core.policies.ensemble  - Predicted next action using policy_2_KerasPolicy
2018-10-17T16:19:15.453614+00:00 app[web.1]: 2018-10-17 16:19:15 DEBUG    rasa_core.processor  - Predicted next action 'utter_sherlock_holmes' with prob 1.00.
2018-10-17T16:19:15.453808+00:00 app[web.1]: 2018-10-17 16:19:15 INFO     rasa_core.channels.facebook  - MessengerBot__init__
2018-10-17T16:19:15.454197+00:00 app[web.1]: 2018-10-17 16:19:15 INFO     rasa_core.channels.facebook  - MessengerBotsend_text_message
2018-10-17T16:19:15.454368+00:00 app[web.1]: 2018-10-17 16:19:15 INFO     rasa_core.channels.facebook  - Sending message: Eh non ! Tu n'as pas résolu cette affaire...
2018-10-17T16:19:15.454582+00:00 app[web.1]: 2018-10-17 16:19:15 INFO     rasa_core.channels.facebook  - MessengerBotsend
2018-10-17T16:19:15.914007+00:00 app[web.1]: POST /me/messages response time 0.01539 s
2018-10-17T16:19:15.914190+00:00 app[web.1]: 2018-10-17 16:19:15 INFO     rasa_core.channels.facebook  - MessengerBotsend_image_url
2018-10-17T16:19:15.914367+00:00 app[web.1]: 2018-10-17 16:19:15 INFO     rasa_core.channels.facebook  - MessengerBotsend
2018-10-17T16:19:17.472491+00:00 app[web.1]: POST /me/messages response time 0.00347 s
2018-10-17T16:19:17.472736+00:00 app[web.1]: 2018-10-17 16:19:17 DEBUG    rasa_core.processor  - Action 'utter_sherlock_holmes' ended with events '[]'
2018-10-17T16:19:17.473128+00:00 app[web.1]: 2018-10-17 16:19:17 DEBUG    rasa_core.processor  - Bot utterance 'BotUttered(text: Eh non ! Tu n'as pas résolu cette affaire..., data: {
2018-10-17T16:19:17.473132+00:00 app[web.1]: "elements": null,
2018-10-17T16:19:17.473133+00:00 app[web.1]: "buttons": null,
2018-10-17T16:19:17.473136+00:00 app[web.1]: "attachment": "https://media.giphy.com/media/yy8WRvsWEyWyI/giphy.gif"
2018-10-17T16:19:17.473138+00:00 app[web.1]: })'
2018-10-17T16:19:17.473949+00:00 app[web.1]: 2018-10-17 16:19:17 DEBUG    rasa_core.policies.memoization  - Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_sherlock_holmes': 1.0}, {'prev_utter_sherlock_holmes': 1.0, 'intent_sherlock_holmes': 1.0}, {'prev_action_listen': 1.0, 'intent_sherlock_holmes': 1.0}, {'prev_utter_sherlock_holmes': 1.0, 'intent_sherlock_holmes': 1.0}]
2018-10-17T16:19:17.474265+00:00 app[web.1]: 2018-10-17 16:19:17 DEBUG    rasa_core.policies.memoization  - There is no memorised next action
2018-10-17T16:19:17.478626+00:00 app[web.1]: 2018-10-17 16:19:17 DEBUG    rasa_core.policies.ensemble  - Predicted next action using policy_2_KerasPolicy
2018-10-17T16:19:17.478851+00:00 app[web.1]: 2018-10-17 16:19:17 DEBUG    rasa_core.processor  - Predicted next action 'action_listen' with prob 1.00.
2018-10-17T16:19:17.479014+00:00 app[web.1]: 2018-10-17 16:19:17 DEBUG    rasa_core.processor  - Action 'action_listen' ended with events '[]'
2018-10-17T16:19:17.479350+00:00 app[web.1]: 
2018-10-17T16:19:17.479353+00:00 app[web.1]: Webhook:
2018-10-17T16:19:17.479356+00:00 app[web.1]: signature 4.7e-05 s
2018-10-17T16:19:17.479358+00:00 app[web.1]: validate 0.000479 s
2018-10-17T16:19:17.479359+00:00 app[web.1]: create_messenger 0.000471 s
2018-10-17T16:19:17.479361+00:00 app[web.1]: handle_messenger 0.04649
2018-10-17T16:19:17.481432+00:00 app[web.1]: 10.61.204.254 - - [2018-10-17 16:19:17] "POST /webhooks/facebook/webhook HTTP/1.1" 200 122 2.038382
2018-10-17T16:19:17.481645+00:00 heroku[router]: at=info method=POST path="/webhooks/facebook/webhook" host=oslo-ia-rasa-bot-us.herokuapp.com request_id=6a493590-4668-4945-ba4b-9165fb5ad98c fwd="31.13.115.11" dyno=web.1 connect=1ms service=2040ms status=200 bytes=122 protocol=https

To be honest, I am not so sure either where to look for the problem, my attempt to time various parts of the rasa_core webhook process have been unsuccessful, and the slack webhook is much faster, so I am sure it doesn't come from Heroku's side.

**Comment by ricwo** [comment] 2018-10-23 12:41
@bbreton3 this is indeed very strange. I will try to reproduce this and will get back to you about this soon

**Comment by ricwo** [comment] 2018-10-23 20:36
@FellowNico @bbreton3 are you using the same NLU and Core models on slack and facebook? I benchmarked the endpoint, and it seems that the majority of time is spent on predicting actions, Note  that I've benchmarked using clock time (`time.time()`) rather than CPU time (`time.clock()`).

Here's the result:
```
validate_hub_signature took 4.67e-05 s
processor._predict_and_execute_next_action 1.8 s
processor._save_tracker took 9.7e-05 s
processor.handle_message took 1.85 s
whole thing took 1.85 s
127.0.0.1 - - [2018-10-23 22:30:15] "POST /webhooks/facebook/webhook HTTP/1.1" 200 122 1.855675
```

as you can see, `processor._predict_and_execute_next_action()` takes up most of the time. So it doesn't look like it's an issue in the facebook connector or Rasa Core

**Comment by bbreton3** [comment] 2018-10-23 21:05
@ricwo , we use the exact same model, and we just comment out the connection info in the `credentials.yml` file to switch between Slack and Facebook (we even tried servicing both at the same time, and the time gap remains between the two platforms).

**Comment by akelad** [comment] 2018-10-24 08:04
Since this is nothing we can sort on our end, I will close this

**Closed by akelad** 2018-10-24 08:04 UTC
