### ISSUE TITLE
Interactive learning with browser output

### ISSUE THREAD

**Issue by phillamarmotte** [RasaHQ/rasa_core#608] opened 2018-06-11 15:36 UTC
Hi,
Is there a way to use something else than the console output for interactive learning ?
Maybe with the CustomChannel class ?

**Comment by phidodido** [comment] 2018-06-23 23:04
I am trying to solve the same problem.

**Issue**:
Using the tips in this [thread](https://github.com/RasaHQ/rasa_core/issues/119) I am able to wrap the bot in a web interface.

`class WebBot(HttpInputComponent)`
`agent.handle_channel(HttpInputChannel(5004, "/", WebBot()))`

Now I want to do the same with interactive learning. I want to have the input/output in a web-based chat UI.

If I try this
`agent.train_online(training_data, input_channel=HttpInputChannel(5004, "/", WebBot()))`
then it only reads the first input in the web UI. Subsequent input can only be done via the console. And all output is displayed in the console, not in the web UI.

**Comment by phidodido** [comment] 2018-06-23 23:10
This the same issue as #343.

**Comment by akelad** [comment] 2018-06-26 08:50
since it's a duplicate of #343 I will close this. As said we are working on a large refactor that should enable this

**Closed by akelad** 2018-06-26 08:50 UTC

**Comment by saqibahmed515** [comment] 2018-07-14 13:56
@akelad #301 (mentioned in #343) seems to be merged quite a while ago. Is it possible now to use interactive learning with HTTP input and output?

**Comment by akelad** [comment] 2018-07-17 14:34
No, I'm afraid not yet - that PR wasn't related to the API
