### ISSUE TITLE
Dialogue training is appending wrong stories to stories.md for no reason

### ISSUE THREAD

**Issue by NicoLivesey** [RasaHQ/rasa_core#415] opened 2018-04-26 09:46 UTC
**Rasa Core version**: 0.8.6

**Python version**:  3.6.3

**Operating system** (windows, osx, ...): Raspbian

**Issue**: Hello everyone, I am currently working on a little project and adapting the supervised learning tutorial, everything work well but one thing is really annoying. When I train the dialogue part (see below) I always find new irrelevant stories appearing in the stories.md.

Here's the training code (relatively basic):

```py
import logging
from rasa_core.agent import Agent
from rasa_core.domain import Domain
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy

if __name__ == '__main__':
    logging.basicConfig(level='INFO')
    dialog_training_data_file = 'stories.md'
    path_to_model = './models/dialogue'
    # domain = Domain()
    agent = Agent('chat_domain.yml', policies = [MemoizationPolicy(), KerasPolicy()])

   agent.train(
        dialog_training_data_file,
        augmentation_factor=50,
        max_history=2,
        epochs=500,
        batch_size=10,
        validation_split=0.2)
    agent.persist(path_to_model)
```

Here's the stories appearing:

```
## Generated Story -5043732597440786429
* bye
    - utter_bye
    - export
## Generated Story 204787383519891157
    - utter_bye
    - export
## Generated Story -5043732597440786429
* bye
    - utter_bye
    - export
## Generated Story 204787383519891157
    - utter_bye
    - export
```

Everytime I want to do a new train I got this like 10 times bigger in stories.md and I have to remove it.

Is it a known bug?

Thank you for the help and for the amazing work!

**Content of domain file** (if used & relevant):
```yml
intents:
    - greet
    - mood
    - who
    - bye
    - contract
    - tips
    - compare
entities:
    - type
    - who
slots:
    type:
        type: text
    who:
        type: text
templates:
    utter_default:
        - 'some string'
    utter_greet:
        - 'some string'
    utter_mood:
        - 'some string'
    utter_who:
        - 'some string'
    utter_bye:
        - 'some string'
    utter_ask_tips_type:
        - 'some string'
    utter_ask_compare_type:
        - 'some string'
    utter_ask_compare_who:
        - 'some string'

actions:
    - utter_default
    - utter_greet
    - utter_who
    - utter_mood
    - utter_bye
    - bot.ActionGetContract
    - bot.ActionGetTips
    - utter_ask_tips_type
    - bot.ActionGetCompare
    - utter_ask_compare_type
    - utter_ask_compare_who
```

**Comment by AbdurRub** [comment] 2018-04-27 07:29
Yes, I noticed it too , So for solution I put my stories file in Data Folder. 
As far my understanding it is related to max_history parameter, it logs history of conversation but I dont even understand logic of that stories.

**Comment by NicoLivesey** [comment] 2018-04-27 08:09
Hi, thank you for your comment. Do you know how this parameter works and how it could be changed in order to prevent this?
I will try your solution but since we can't permanently change the path of the interactive training's output it is a bit annoying...

Anyway thank you !

**Comment by NicoLivesey** [comment] 2018-04-27 08:40
Ok I understood it now thank you so it's not a bug the training is just adding additionnal data to stories.md

**Comment by AbdurRub** [comment] 2018-04-27 09:15
Its Bug! :D Phew.

**Comment by rojobuffalo** [comment] 2018-04-28 16:42
Are the stories irrelevant or just unexpected? It looks like they are coming from your domain file. 

My experience is the interactive training asks you where you want to export generated stories and defaults to `projectroot/stories.md`. This is a separate file from the training file in `data/stories.md` which the agent is trained on. It is up to you to merge which ever stories you want from the generated file into your training file (`data/stories.md`). There is a parameter `max_training_samples` which controls how many generated stories are included in the `/stories.md` file. Seen in example here: https://github.com/RasaHQ/rasa_core/blob/bdc3a79c9f7580ceee73d5a657b5e9fdf289c7b3/examples/concertbot/train_online.py#L30

cc #39

**Comment by NicoLivesey** [comment] 2018-04-30 08:14
Hi @rojobuffalo, thank you for your reply. Here I am not talking about the output of the interactive training which behavior is pretty normal. I only observe that when I train a dialogue model (not necessarily an interactive training) it generates artificial stories inpired by my previous stories with the length limit parameter `max_history` on the train function of `Agent` and I don't understand if this behavior is mandatory or can we disable it because it obviously adds irrelevant stories that I need to remove everytime.

**Comment by rojobuffalo** [comment] 2018-04-30 14:18
@NicoLivesey ok, thanks for clarifying.

**Comment by tmbo** [comment] 2018-05-14 16:03
This was an issue, that should be fixed on the latest master.

**Closed** 2018-05-14 16:02 UTC
Labels: bug

**Comment by Harish238** [comment] 2018-05-23 06:38
Hi guys. I know the issue is closed, but I tried all the solutions here and it did not work for me.

When I inspected the `data/stories.md` file which contained my exported stories, the constituent stories also contained the action `- export`. So I removed this action in every story present in the file and the issue seemed to be resolved. The wrong stories are not appended anymore.

As to why this happened, I used the same stories file with the `- export` action for further interactive trainings and I suspect that this must have been the reason for the wrong stories being appended.

**Comment by tmbo** [comment] 2018-05-23 07:09
Are you using the latest master? This should be fixed there, but not yet in the version that is available on pypi.

**Comment by rojobuffalo** [comment] 2018-05-23 16:01
@Harish238 I was under the impression that the `- export` lines at the end of each action were ok to leave in. I figured it was used to note that the story was generated from training rather than hand-written. I haven't noticed any issues stemming from including or removing it so I figured those lines were just ignored. Am I mistaken?

**Comment by rojobuffalo** [comment] 2018-05-27 04:29
I just upgraded to latest rasa_core (0.9.0) and now when I hit `<enter>` at the end of training, expecting it to write output to `./stories.md`, nothing is written at all. Console shows:
```
File to export to (if file exists, this will append the stories) [stories.md]: 
2018-05-26 23:24:07 INFO     rasa_core.policies.online_trainer  - Stories got exported to '/Users/myhomefolder/Code/mybot'.
```
But there is no file `./stories.md`. If I specify the output destination, like `data/stories.md`, it will properly append the new stories. Just hitting `<enter>` writes nothing, but says that it did. If I specify `stories.md`, this will actually write it.

Is this a bug?

**Comment by tmbo** [comment] 2018-05-28 07:39
Yes good catch, I created a PR to fix that :+1: https://github.com/RasaHQ/rasa_core/pull/543

**Comment by tarunbhavnani** [comment] 2018-11-15 09:12
stories not updating to stories.md
## Generated Story 0

**Comment by tmbo** [comment] 2018-11-19 13:02
please create a new issue explaining **in detail** what the issue is you are observing as well as a log file.
