### ISSUE TITLE
Model Training fails when after defining parameters in 'config.yml' file.

### ISSUE THREAD

**Issue by vishnuragas** [RasaHQ/rasa_core#1525] opened 2018-12-28 20:09 UTC
**Rasa Core version**: 0.13.0a4

**Python version**: 3.6.1

**Operating system**: Windows 10

**Issue**:

I faced the same issue as in https://github.com/RasaHQ/rasa_core/issues/1501. I created a new file 'config.yml' to pass the parameters and ran the 'train command' as below:

`python -m rasa_core.train -d domain.yml -s data/stories.md -o models/current/dialogue -c config.yml`

Once I executed the command, I got the below error. I have attached the traceback too.

![traceback](https://user-images.githubusercontent.com/28904290/50526785-6109cf00-0ab2-11e9-8dfe-000aae5c2702.PNG)

**Comment by wochinge** [comment] 2019-01-02 08:43
This seems to be a TensorFlow problem (https://github.com/tensorflow/tensorflow/issues/23368). Did you use the GPU version of TensorFlow? And if so, can you please try to the suggested workarounds from the TensorFlow issue?

**Comment by vishnuragas** [comment] 2019-01-07 15:36
@wochinge No, I did not use the GPU version. The workarounds (installing TF 1.9.0 did not work)

**Comment by wochinge** [comment] 2019-01-07 16:44
@MetcalfeTom We need another Windows user here. Could you please check that on your machine?

**Comment by MetcalfeTom** [comment] 2019-01-08 10:08
Copied your code and was unable to reproduce the error, which leads me to believe this has to be a Tensorflow issue

**Comment by vishnuragas** [comment] 2019-01-08 21:14
As in https://github.com/RasaHQ/rasa_core/issues/1501, I tested both methods, Passing the parameters to Policy_Config.yml file, and to KerasPolicy(). In both instances, I got the same error.

Dialogue_management.py contains the following code:
```

from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import logging
import rasa_core
from rasa_core.agent import Agent
#from rasa_core.channels.console import ConsoleInputChannel
from rasa_core.interpreter import RegexInterpreter
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_core.utils import EndpointConfig
from rasa_core.run import serve_application


logger = logging.getLogger(__name__)

def train_dialogue(domain_file = 'domain.yml',
                   model_path = './models/dialogue',
                   training_data_file = './data/stories.md'):
    agent = Agent(domain_file, policies = [MemoizationPolicy(), KerasPolicy( 
				epochs = 300,
                batch_size = 50,
                validation_split = 0.2)])
    data = agent.load_data(training_data_file)
    agent.train(data)
    agent.persist(model_path)
    return agent

	
def run_product_bot(serve_forever=True):
	interpreter = RasaNLUInterpreter('./models/nlu/default/ssbot')
	action_endpoint = EndpointConfig(url="http://localhost:5055/webhook")
	agent = Agent.load('./models/dialogue', interpreter=interpreter, action_endpoint=action_endpoint)
	rasa_core.run.serve_application(agent ,channel='cmdline')
		
	return agent
	
if __name__ == '__main__':
	train_dialogue()
	run_product_bot()

```

**Comment by vishnuragas** [comment] 2019-01-10 18:00
[req.txt](https://github.com/RasaHQ/rasa_core/files/2746526/req.txt)

@MetcalfeTom Hi, I used Tensorflow 1.10.0. What is the tensorflow version you tested on? Above is the list of packages in the environment I tried to execute the code.

**Comment by MetcalfeTom** [comment] 2019-01-18 13:01
`1.10.0` same as you.

I'm not certain why this error crops up, but there was a large thread about it on [tensorflow's repo](https://github.com/tensorflow/tensorflow/issues/20320) and the following advice seemed to work:

> Go to the tensorflow directory e.g `D:\anaconda\lib\site-packages\tensorflow\contrib\data`
> 
> Inside, you will find a file named `_dataset_ops.so` - delete this file or move it out of this folder and re run the code

I hope this works for you.  I'll have to close this since it's not an issue on our end

**Closed by MetcalfeTom** 2019-01-18 13:01 UTC
