### ISSUE TITLE
Is there a way to perform an action as soon as the bot is loaded?

### ISSUE THREAD

**Issue by devansh1497** [RasaHQ/rasa_core#719] opened 2018-07-10 12:05 UTC
**Rasa Core version**:0.8

**Python version**: 3.6.4

**Operating system** (windows, osx, ...):OSX

**Issue**:
Currently the very first action that the bot performs when it is loaded is that it waits for the user to type something.I would like to change that.I would like the user to choose between one of the topics to perform the next actions on.For this purpose, I would like provide the user with 3 buttons(one for each option).Then, I would like to fill a slot value(depending upon what button the user chose)...So, how do I force the user to choose an option using buttons as soon as the bot is loaded and how do I set a slot value when the user presses a specific button?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by devansh1497** [comment] 2018-07-10 13:05
@akelad I will be integrating my bot with Slack. Can you please tell me how to do it?Also, how do I set a slot through buttons?For example - I have a slot "topic.".Now if the user choose button 'A',then I would like to set slot topic to A. If he chooses B, then the slot should be 'B' and so on.

**Comment by akelad** [comment] 2018-07-10 16:17
@devansh1497 here is the documentation for connecting rasa core to slack: https://core.rasa.com/connectors.html#slack-setup
As for sending an initial message - I'm not sure that's possible with slack, you'd have to do some digging through their documentation

About setting slots with buttons, if you name the entity the same as your slot, you can do this by setting the payload to be something like `/intent_name{"entity_name":"entity_value"}`
If they don't have the same name, you have to create a custom action that sets the slot for you

**Comment by devansh1497** [comment] 2018-07-10 16:19
@akelad Actually I already know how to integrate with slack...I was just wondering if it is possible to set a custom action as the load up action.

**Comment by arachny** [comment] 2018-07-10 16:34
When you use Slack the first action will be from the user initiating the dialogue. So what I have done is to subclass the Action class (and also other like FormAction) and eventually run my custom code in the `run` function. Since each user has a unique id you will be able to keep track of what users have initiated a dialogue and eventually perform your logic.

**Comment by devansh1497** [comment] 2018-07-11 05:47
@arachny Can you please elaborate?What are the steps needed?

**Comment by arachny** [comment] 2018-07-12 13:12
For example I subclassed the Action class as:
```
class MyAction(Action):
    def run(self, dispatcher, tracker, domain):
        # get user id
        uid = dispatcher.sender_id
        
        # get a slot (if needed, so you can check if it has an initial value)
        myslot = tracker.get_slot("slot")

        # update a slot value (with any value, e.g. from a DB)
        tracker.update(SlotSet("myslot", "some value"))

        # get the return from your class implementation (so you can still use your specialised actions)
        returns = self.myrun(dispatcher, tracker, domain)
        
        return returns

    def myrun(self, dispatcher, tracker, domain):
        return []
```

So this (MyAction) will be executed for ALL actions as long as you use that instead of the Action class. E.g.:
```
class ActionCustom(MyAction):
    def name(self):
        return "action_custom"

    def myrun(self, dispatcher, tracker, domain):
        # ... code
        return []
```

Make sure you have the appropriate if statement in place so MyAction does not execute the logic all the time.

**Comment by akelad** [comment] 2018-07-17 14:38
@arachny this doesn't let the bot initiate the conversation though right? @devansh1497 if there's no function in slack to force the initial user message to be a specified message then i'm afraid it's not possible

**Comment by arachny** [comment] 2018-07-17 14:46
I agree, that is why I said that it will only be executed after the user interacts (i.e. Slack, as @devansh1497 intended). So in the first interaction the method will be triggered to setup the customised environment based on the user that initiates the chat. Potentially there could even be an initial utter sent to inform the user that the system is initialising (if that takes time).

Otherwise as @akelad said, there is no other way to initiate this.

**Comment by akelad** [comment] 2018-07-19 08:59
Alright, I just noticed this is a duplicate of #585 - if you have any other questions, please continue the discussion there :)

**Closed by akelad** 2018-07-19 08:59 UTC
Labels: question
