### ISSUE TITLE
Invalid story file format

### ISSUE THREAD

**Issue by sameerkumar16** [RasaHQ/rasa_core#228] opened 2018-02-16 14:54 UTC
**Rasa Core version**:0.8.2,

**Python version**: 3.6

**Operating system**:ubuntu 14.04

**Issue**:
I am training on some stories. But I can't. It's throwing 
```
ValueError: Invalid story file format.
```

**Content of stories  file** (if used & relevant):
```
## 1
* greet
  - utter_greet
* ask_about{"info": "Domain"}
  - action_ask_about
  - utter_more
* deny
  - utter_bye

## 2
* greet
  - utter_greet
* ask_about{"info": "Demo"}
  - action_ask_about
  - utter_more
* affirm
  - utter_affirm

## 3
* greet
  - utter_greet
* ask_about{"info": "Support"}
  - action_ask_about
  - utter_more
* affirm
  - utter_affirm

## 4
* greet
  - utter_greet
* ask_about{"info": "Competitors"}
  - action_ask_about
  - utter_more
* affirm
  - utter_affirm
* bye 
  - utter_bye

```

**Comment by znat** [comment] 2018-02-16 15:22
this error is triggered when an action in your stories is not found in the domain.

**Comment by sameerkumar16** [comment] 2018-02-16 16:22
I have checked all the actions in the domain still It's not working

**Comment by poorni19** [comment] 2018-02-16 17:39
can you post your yml file as well ? @sameerkumar16

**Comment by sameerkumar16** [comment] 2018-02-16 17:53
@poorni19  I solved this issue .Just by rewriting the story .I couldn't figure out what was wrong.

**Comment by poorni19** [comment] 2018-02-16 18:04
@sameerkumar16 yes..same happened with me ..Good that you were able to solve it. Are you using FB to deploy the bot ?

**Comment by sameerkumar16** [comment] 2018-02-16 18:13
@poorni19 .No on a website .

**Comment by tmbo** [comment] 2018-02-16 19:43
Usually there should be a line attached to that error (or mentioned in the logs before that exception gets raised)

**Comment by znat** [comment] 2018-02-17 12:32
@tmbo Yes, but the generic error only is displayed in the console. To know exactly what the problem is, you need to breakpoint in `process_lines()`

**Comment by tmbo** [comment] 2018-02-23 10:44
Without a complete example, we can not reproduce this. So I will close this - I am having a look at the error reporting right now though to make sure the line in the file is properly reported.

**Closed by tmbo** 2018-02-23 10:44 UTC

**Comment by Faadal** [comment] 2018-08-03 10:50
Agree with @znat, I have had the same error. After checking I found that I mistype an action. Thanks

**Comment by nuronics** [comment] 2018-12-17 09:12
even am facing the same problem i have  downloaded the story from the rasacore github 
![rasastory](https://user-images.githubusercontent.com/42369707/50077270-f501ae00-0209-11e9-8e58-e0c3641b1467.png)
site
am using rasa_core 0.8.2 and nlu 0.11.4
any help is appreciated thanks in advance

**Comment by tmbo** [comment] 2018-12-18 10:54
Did you download the data for the 0.8.2 version as well, or did you download from the master branch?
