### ISSUE TITLE
How to work with FormAction?

### ISSUE THREAD

**Issue by ewagner70** [RasaHQ/rasa_core#435] opened 2018-05-03 21:42 UTC
**Rasa Core version**: 0.9.0a3
**Rasa NLU version**: 0.12.2

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu 17.10

**Issue**: I'm obviously too stupid to work with newly introduced FormAction for easier filling in slots and not generating numerous stories (details see files below).
The bot got stuck after trigger sentence "I want to report a conflict of interest". Then no reply (no matter what I enter)
when I enter fallback sentence, then 10 times the fallback reply comes back.

Can you provide a simple comprehensive example on how to use FormAction (your partial examples seem to lack some key information or I'm simply too stupid to understand it), ideally complemented with an example on how to fill the slot with the "coi_gi_receivername" (!)
Thx in advance!

**Content of domain file** (if used & relevant):
```georgebot_domain.yml
intents:
 - greet
 - default
 - goodbye
 - thankyou
 - reportcoi
 - affirm
 - inform

entities:
 - username

slots:
  username:
    type: text
    initial_value: "human"
  slot_result:
    type: text
  requested_slot:
    type: unfeaturized


templates:
  utter_greet:
    - "hey there {username}!"    # variable will be filled by slot with the same name or by custom code
  utter_goodbye:
    - "goodbye {username}"       # multiple templates will allow the bot to randomly pick from them
  utter_default:
    - "I don't understand what you mean!"
  utter_affirm:
    - "affirmative"
  utter_thankyou:
    - "you're welcome"
  utter_entername:
    - "Good to know you, {username}"
  utter_reportcoi:
    - "Sure, let me guide you through the reporting process."
  utter_coi_gi_receivername:
    - "Who is the receiver of the gift/invitation?"
  utter_coi_gi_give_or_take:
  - text: "Do you give or receive the gift/invitation to {coi_gi_receivername}?"
    buttons:
    - title: "give"
      payload: "give"
    - title: "receive"
      payload: "receive"
  utter_coi_amount:
    - "How much is the gift/invitation worth (in EUR)?"
  utter_coi_gi_is_publicofficial:
    - "Is the receiver/giver a public official?"
  utter_coi_remarks:
    - "Please amend any further information necessary"

actions:
  - utter_greet
  - utter_default
  - utter_goodbye
  - utter_thankyou
  - utter_reportcoi
  - utter_affirm
  - utter_entername
  - utter_coi_gi_receivername
  - utter_coi_gi_give_or_take
  - utter_coi_gi_is_publicofficial
  - utter_coi_amount
  - utter_coi_remarks
  - test_rasa.ActionReportCoI
```
```test_rasa.py
class ActionReportCoI(FormAction):

    RANDOMIZE = False

    @staticmethod
    def required_fields():
        return [
            EntityFormField("coi_gi_receivername", "coi_gi_receivername"),
            EntityFormField("coi_gi_give_or_take", "coi_gi_give_or_take"),
            EntityFormField("coi_gi_is_publicofficial", "coi_gi_is_publicofficial"),
            EntityFormField("coi_amount", "coi_amount")
        ]

    def name(self):
        return 'action_report_coi'

    def submit(self, dispatcher, tracker, domain):
        results = RestaurantAPI().search(
            tracker.get_slot("coi_gi_receivername"),
            tracker.get_slot("coi_gi_give_or_take"),
            tracker.get_slot("coi_gi_is_publicofficial"),
            tracker.get_slot("coi_amount"))
        return [SlotSet("search_results", results)]
```
```georgebot_nlu.md
## intent:greet
- good morning
- good evening
- hey
- howdy
- hey there
- hello
- hi
- dear sir

## intent:default
- bla bla
- do you want to marry me
- i hate you
- i want something else
- can you help me?
- do you love me?
- fuck you

## intent:goodbye
- goodbye
- good bye
- stop
- end
- farewell
- Bye bye
- have a good one

## intent:affirm
- great
- right, thank you
- correct
- great choice
- sounds really good
- yes
- yep
- yeah
- indeed
- that's right
- ok

## intent:reportcoi
- report conflict of interest
- i would like to report a conflict of interest
- i want to report a conflict
- how can i report a conflict of interest
- where can i report a conflict of interest
- can you support me in reporting a conflict of interest

## intent:intent_coi_gi_receivername
- the receiver's name is [Eric Wagner](coi_gi_receivername)
- the name is [Karin](coi_gi_receivername)
- my name is [Philipp Mayer](coi_gi_receivername)
- the receiver will be [Oliver Mueller](coi_gi_receivername)
- the receiver is [Constantine Breitenfeld](coi_gi_receivername)

## intent:thankyou
- thanks
- thank you
- thank you very much
- nice
- thx alot
- thx
- appreciated

## synonym:chinese
+ Chines
* Chinese

## synonym:vegetarian
- vegg
- veggie

## regex:zipcode
- [0-9]{5}

## regex:greet
- hey[^\s]*
```
```georgebot_stories.md
## greet path
* greet
  - utter_greet

## goodbye path
* goodbye
  - utter_goodbye

## default path
* default
  - utter_default

## affirm path
* affirm
  - utter_affirm

## thankyou path
* thankyou
  - utter_thankyou

## report_coi path 1
* reportcoi
  - action_report_coi
  - slot{"requested_slot": "coi_gi_give_or_take"}
* inform("coi_gi_give_or_take": "give")
  - action_report_coi
  - slot{"requested_slot": "coi_gi_is_publicofficial"}
* inform{"coi_gi_is_publicofficial": "affirm"}
  - action_report_coi
  - slot{"requested_slot": "coi_amount"}
* inform{"coi_amount": "1000"}
  - action_report_coi
  - utter_goodbye
```

**Comment by ewagner70** [comment] 2018-05-04 21:50
Guys ... any chance for feedback? Does this FormAction really work? Did anybody succeed in bringing that to life?

**Comment by tmbo** [comment] 2018-05-05 11:40
Does the `report_coi path 1` not work either if you try to follow it with the trained bot?

**Comment by ewagner70** [comment] 2018-05-05 12:33
I'm not sure, as I don't get any feedback from bot - prompt remains and I can enter further input(s) with same effect. This stops when I only hit the enter (i.e. no input) and then 10 times the utter_default appears. Then I can start over with "hi" again (which works, by the way). Only if I enter the report_coi_path 1, I have the above mentioned effects.

**Comment by tmbo** [comment] 2018-05-05 12:45
Can you run the bot with `--debug` flag set to increase the output? If you don't mind, please also add the comandline log from this session.

**Comment by ewagner70** [comment] 2018-05-05 18:34
2018-05-05 20:32:10 INFO     rasa_core.policies.keras_policy  - Done fitting keras policy model
2018-05-05 20:32:10 INFO     rasa_core.agent  - Persisted model to '/home/eric/data/test_rasa/models/dialogue'
2018-05-05 20:32:10 INFO     rasa_nlu.components  - Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Bot loaded. Type a message and press enter: 
hi
2018-05-05 20:32:21 DEBUG    rasa_core.tracker_store  - Creating a new tracker for id 'default'.
2018-05-05 20:32:21 DEBUG    rasa_core.processor  - Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.5368560066640731}' and entities '[]'
2018-05-05 20:32:21 DEBUG    rasa_core.processor  - Logged UserUtterance - tracker now has 2 events
2018-05-05 20:32:21 DEBUG    rasa_core.processor  - Current slot values: 
	requested_slot: None
	slot_result: None
	username: human
2018-05-05 20:32:21 DEBUG    rasa_core.policies.memoization  - Current tracker state [
	[('slot_username_0', 1)]
	[('intent_greet', 1), ('slot_username_0', 1), ('prev_action_listen', 1)]]
2018-05-05 20:32:21 DEBUG    rasa_core.policies.memoization  - Used memorised next action '2'
2018-05-05 20:32:22 DEBUG    rasa_core.policies.ensemble  - Predicted next action 'utter_greet' with prob 1.00.
hey there human!
2018-05-05 20:32:22 DEBUG    rasa_core.processor  - Bot utterance 'BotUttered(text: hey there human!, data: null)'
2018-05-05 20:32:22 DEBUG    rasa_core.processor  - Action 'utter_greet' ended with events '[]'
2018-05-05 20:32:22 DEBUG    rasa_core.policies.memoization  - Current tracker state [
	[('intent_greet', 1), ('slot_username_0', 1), ('prev_action_listen', 1)]
	[('intent_greet', 1), ('slot_username_0', 1), ('prev_utter_greet', 1)]]
2018-05-05 20:32:22 DEBUG    rasa_core.policies.memoization  - Used memorised next action '0'
2018-05-05 20:32:22 DEBUG    rasa_core.policies.ensemble  - Predicted next action 'action_listen' with prob 1.00.
2018-05-05 20:32:22 DEBUG    rasa_core.processor  - Action 'action_listen' ended with events '[]'
2018-05-05 20:32:22 DEBUG    rasa_core.processor  - Current topic: None
I want to report a conflict of interest
2018-05-05 20:32:55 DEBUG    rasa_core.tracker_store  - Recreating tracker for id 'default'
2018-05-05 20:32:56 DEBUG    rasa_core.processor  - Received user message 'I want to report a conflict of interest' with intent '{'name': 'reportcoi', 'confidence': 0.517626934387094}' and entities '[]'
2018-05-05 20:32:56 DEBUG    rasa_core.processor  - Logged UserUtterance - tracker now has 6 events
2018-05-05 20:32:56 DEBUG    rasa_core.processor  - Current slot values: 
	requested_slot: None
	slot_result: None
	username: human
2018-05-05 20:32:56 DEBUG    rasa_core.policies.memoization  - Current tracker state [
	[('intent_greet', 1), ('slot_username_0', 1), ('prev_utter_greet', 1)]
	[('intent_reportcoi', 1), ('slot_username_0', 1), ('prev_action_listen', 1)]]
2018-05-05 20:32:56 DEBUG    rasa_core.policies.memoization  - Used memorised next action '14'
2018-05-05 20:32:56 DEBUG    rasa_core.policies.ensemble  - Predicted next action 'action_report_coi' with prob 1.00.
2018-05-05 20:32:56 ERROR    rasa_core.processor  - Encountered an exception while running action 'action_report_coi'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
2018-05-05 20:32:56 ERROR    rasa_core.processor  - name 'EntityFormField' is not defined
Traceback (most recent call last):
  File "/home/eric/.local/lib/python3.6/site-packages/rasa_core/processor.py", line 301, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/eric/.local/lib/python3.6/site-packages/rasa_core/actions/forms.py", line 118, in run
    events = self.get_requested_slot(tracker) + self.get_other_slots(tracker)
  File "/home/eric/.local/lib/python3.6/site-packages/rasa_core/actions/forms.py", line 100, in get_requested_slot
    required = self.required_fields()
  File "/home/eric/data/test_rasa/test_rasa.py", line 60, in required_fields
    EntityFormField("coi_gi_receivername", "coi_gi_receivername"),
NameError: name 'EntityFormField' is not defined
2018-05-05 20:32:56 DEBUG    rasa_core.processor  - Action 'action_report_coi' ended with events '[]'
2018-05-05 20:32:56 DEBUG    rasa_core.policies.memoization  - Current tracker state [
	[('intent_reportcoi', 1), ('slot_username_0', 1), ('prev_action_listen', 1)]
	[('intent_reportcoi', 1), ('slot_username_0', 1), ('prev_action_report_coi', 1)]]
2018-05-05 20:32:56 DEBUG    rasa_core.policies.memoization  - Used memorised next action '0'
2018-05-05 20:32:56 DEBUG    rasa_core.policies.ensemble  - Predicted next action 'action_listen' with prob 1.00.
2018-05-05 20:32:56 DEBUG    rasa_core.processor  - Action 'action_listen' ended with events '[]'
2018-05-05 20:32:56 DEBUG    rasa_core.processor  - Current topic: None

**Comment by ewagner70** [comment] 2018-05-08 19:28
Guys ... any help would be appreciated.

**Comment by akelad** [comment] 2018-05-09 09:12
So as for 1:
You have to set the payload to "/give" - this directly passes on the intent.
How are you sending this utterance? Is it with dispatcher.utter_button_template? If it's with dispatcher.utter_button_message, you have to `.format` the string with the slot value. With the template it should be set automatically though.

2. I'd say you have to add stories for the fallback action then.

**Comment by ewagner70** [comment] 2018-05-10 08:33
I have to be honest - you've lost me ...

ad 1a) there's no  "give". I simply want to fill the slot "coi_gi_give_or_take" with either "give" or "receive". Ideally, I would like to do that with a button, but I don't know how that works with FormAction?
ad 1b) can you help me on that as well?

ad 2) 
- do you really mean separate STORIES for fallback action? If yes, HOW do I do that ??
- I thought separate intent examples in nlu.yml are sufficient for that?  (see attached .zip file above with complete py and yml and md file-set)

ad 3a+b) can you help me on that as well?

**Comment by amn41** [comment] 2018-05-14 07:13
https://github.com/RasaHQ/rasa_core/pull/458 should fix the slot issue

**Comment by amn41** [comment] 2018-05-14 07:16
for 1a) if you want a button to pass entities you can also do that, with e.g. `/coi_gi_give_or_take{"give_take":"give"}` as a payload (assuming you have an entityformfield which sets entity `give_take` to the slot you want to set.

**Comment by amn41** [comment] 2018-05-14 18:45
easiest is just to grab master from github

**Comment by ewagner70** [comment] 2018-05-14 20:30
I'm too stupid ...
sudo -H python3 setup.py install --user
installs everything in (correct) ~/.local/lib/python3.6/site-packages/ 
EXCEPT rasa_core, which is installed under /root/.local/lib/python3.6/site-packages/ (!?)
see: 
<pre><font color="#8AE234"><b>root@fractal</b></font>:<font color="#729FCF"><b>/root/.local/lib/python3.6/site-packages</b></font># ls -l
total 300
-rw-r--r-- 1 root root    220 Mai 14 22:20 easy-install.pth
-rw-r--r-- 1 root root 295766 Mai 14 22:20 rasa_core-0.9.0a5-py3.6.egg
-rw-r--r-- 1 root root     46 Mai 14 22:20 setuptools.pth
<font color="#8AE234"><b>root@fractal</b></font>:<font color="#729FCF"><b>/root/.local/lib/python3.6/site-packages</b></font># cat easy-install.pth 
./rasa_core-0.9.0a5-py3.6.egg
/usr/local/lib/python3.6/dist-packages/colorhash-1.0.2-py3.6.egg
/home/eric/.local/lib/python3.6/site-packages
/usr/local/lib/python3.6/dist-packages/tensorflow-1.8.0-py3.6-linux-x86_64.egg
<font color="#8AE234"><b>root@fractal</b></font>:<font color="#729FCF"><b>/root/.local/lib/python3.6/site-packages</b></font># cat setuptools.pth 
/home/eric/.local/lib/python3.6/site-packages
</pre>

**Comment by akelad** [comment] 2018-06-06 08:04
You need to add the name `requested_slot` to your slots in the domain file

**Comment by Egalite123** [comment] 2018-06-07 14:12
Thank you! The error disappeared. Wish the documentation was little clear. Did not realize the slot name it self was, "requested_slot'

**Comment by amn41** [comment] 2018-06-07 14:16
+1 we should raise an error if a domain contains a `FormAction` but there is no `requested_slot` in the domain

**Comment by Egalite123** [comment] 2018-06-21 11:54
another suggestion / request : 
Is it possible to pull the VALIDATE function from forms.py and be referenced / called from custom actions?
Though this validations implementation is nice, don't like some custom code creeping in core packages.

**Comment by Egalite123** [comment] 2018-06-21 18:10
I made some progress. I am able to get the validations properly. It  does go to the submit function after the last action_fillForm. But, story does not go to "utter_goodbye". Is this a training issue or something else?
I am yet to locate a proper example to see, if I am at least on the right track.

My story ends like this...

....
....
....
  - action_fillForm
  - slot { "requested_slot": "addr"}
* nameNo {"addr":"103, 1xxxxx"}
  - action_check
  - action_write
  - action_fillForm
  - slot { "requested_slot": "idProof"}
* nameNo {"idProof":"xxxxx"}
  - action_fillForm
  - utter_goodbye
  - action_restart

**Comment by Egalite123** [comment] 2018-07-02 02:57
@ewagner70 , did you manage to get this working. Been doing several attempts and also finding very similar to your observations.

**Comment by ewagner70** [comment] 2018-07-02 16:46
@Egalite123 yes, I've downloaded the most recent version from github (via `pip install -U git+https://github.com/rasahq/rasa_core.git --user` ) what I found out is that the training set is sometimes quite tricky to compose (if you are referring to your last comment "... but story does not go to 'utter_goodbye' ...") especially if you have lengthy similar paths in various stories and it can sometimes lead to a shitty model, which does not really work (then simply re-train again and re-use that model accordingly)
Don't know if my answer really helps - maybe you can be more specific which of the aboves issues you're referring to.

**Comment by Primtek** [comment] 2018-07-04 00:17
@Egalite123  could you please share your project here.. I am facing the same issue :(

**Comment by eleow** [comment] 2018-07-11 10:11
@Egalite123  I am having the same issue as well. It goes into submit form but does not go into the next action.

**Comment by akelad** [comment] 2018-07-17 14:48
could one of you share your stories file/form action so we can try and reproduce this? In general it might help to try interactive learning for this. It might be that you've forgotten a slot set event somewhere in your stories

**Comment by Egalite123** [comment] 2018-07-18 13:14
Hi @akelad , here is my stories file.
When I run the bot, I do get "success". But, does not goto "utter_otp".
Please let me know, if you need anything more.

## FundsTransferConfirm
* transferFunds
    - action_fillForm
    - slot{"requested_slot": "fromAccount"}
* dataInput
    - action_fillForm
    - slot{"fromAccount": "A0001"}
    - slot{"requested_slot": "toAccont"}
* dataInput
    - action_fillForm
    - slot{"toAccount": "B0002"}
    - slot{"requested_slot": "currency"}
* dataInput
    - action_fillForm
    - slot{"currency": "USD"}
    - slot{"requested_slot": "amt"}
* dataInput
    - action_fillForm
    - slot{"amt": "1000"}
    - slot{"searchResults": "success"}
    - utter_otp
* otp
    - utter_confirmTransfer
    - action_restart


actions.py -->

class trustCheck(object):
    def search(self, *args):

        print ("= = = = inside api  = = = = =")
        return

class ActionFillForm(FormAction):

    RANDOMIZE = False
    print ("Surya...")
    @staticmethod
    def required_fields():
        return [
            FreeTextFormField("fromAccount"),
            FreeTextFormField("toAccount"),
            FreeTextFormField("currency"),
            FreeTextFormField("amt")
        ]

    def name(self):
        return ACTION_FILLFORM

    def submit(self, dispatcher, tracker, domain):


        results = trustCheck().search(
            tracker.get_slot("fromAccount"),
            tracker.get_slot("toAccount"),
            tracker.get_slot("currency"),
            tracker.get_slot("amt"))

        template = "utter_thanks"
        dispatcher.utter_template(template)

        results = "success"
        print ("==== in submit =====")
        print ("Results...... ", results)
        return [SlotSet("searchResults",results)]

**Comment by Egalite123** [comment] 2018-07-19 07:21
In continuation of the above, while testing last night noticed this - 
a. While I just start with intent (in this example - just saying "transfer funds" with out entities) and if I let FormAction control the dialogue with the user (filling all slots sequentially), it is behaving normally and goes onto "utter_otp"
b. If I start with something like - "transfer 100 from my account AC1234", bot identifies that , two slots amt and fromAccount are filled and asks only currency and toAccount. In this case, though the FormAction has all the entities, it does out come of the loop and goes to "utter_otp".

May be this is a clue. But, was still elusive to me.

**Comment by akelad** [comment] 2018-07-19 08:31
Ah ok, so the issue here is you need to have a story for that case too, when the user provides some information at the start already. Otherwise Core may not have the correct prediction

**Comment by Egalite123** [comment] 2018-07-19 17:35
Not sure, I follow you. But, when the user supplies other info (e.g., amount ), I see that the required slot is already is filled and FormAction skips the question. That is an expected behaviour, right?

**Comment by akelad** [comment] 2018-07-24 16:04
Yes it is, but you also need to add the stories for those cases to your training data otherwise future predictions of core might be wrong.

**Comment by eleow** [comment] 2018-08-10 03:49
If i have fields in the FormAction that are more or less identical in its range and type of values, how do I train my NLU to recognise the correct intent for it. Eg inform{"latitude": "10"} vs inform{"longitude": "10"}. Is there any way for me to automatically force whatever input the user has to a particular intent?

**Comment by eleow** [comment] 2018-08-10 03:51
> could one of you share your stories file/form action so we can try and reproduce this? In general it might help to try interactive learning for this. It might be that you've forgotten a slot set event somewhere in your stories

Strangely, in interactive learning, it seems to be executing it correctly.

**Comment by akelad** [comment] 2018-08-10 08:05
what do you mean? Those examples have the same intent, are you talking about entities?

**Comment by Egalite123** [comment] 2018-08-10 17:16
I have hit up on a problem. I have two different  story snippets (or, use cases). One FormAction to make a FundsTransfer and another one to collect user information for call back. I have named them two different action names and also two different intents to collect user inputs (one like illustrated above - "dataInput" and  other formAction has "inform" intents - just to avoid confusion. 
Both the flows collect numerical data (like amount in the example above and other form action also collects customer account number). 
Some times, while running, bot picks up the other intent (instead of "dataInput" picks the intent as "inform" and jumps into the middle of other story.
How can I avoid this situation?

**Comment by akelad** [comment] 2018-08-13 07:31
@Egalite123 Can you post this kind of question in our [forum](forum.rasa.com) please? We'll answer it there.
Also this issue thread has been going on for a while and they're all mostly questions rather than issues/bugs, so I'll close this for now.

**Closed by akelad** 2018-08-13 07:31 UTC
Labels: question
